# SPDX-FileCopyrightText: © 2025 Swifter Sash Spaan. All Rights Reserved.
# SPDX-License-Identifier: LicenseRef-AllRightsReserved

repos:
-   repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
    -   id: reuse
